from typing import TypedDict, List
from .Regions import Chapters
from .Options import RE5Options, ExcludeDriving


class LocationDict(TypedDict):
    name: str
    chapter: Chapters
    arc_file: str
    ap_id: float


class EventDict(TypedDict):
    name: str
    chapter: str
    item: str


location_table: List[LocationDict] = [
    {'name': "1-2 Old Building Key",
        'chapter': Chapters.c12_urban,
        'arc_file': "s102.arc",
        'ap_id': 4861001},
    {'name': "1-2 Handgun Ammo on Table before Old Building Key",
        'chapter': Chapters.c12_urban,
        'arc_file': "s102.arc",
        'ap_id': 4861002},
    {'name': "1-2 First Aid Spray on Table Balcony Building F2",
        'chapter': Chapters.c12_urban,
        'arc_file': "s102.arc",
        'ap_id': 4861003},
    {'name': "1-2 Antique Clock in Chest Balcony Building F2",
        'chapter': Chapters.c12_urban,
        'arc_file': "s102.arc",
        'ap_id': 4861004},
    {'name': "1-2 Ithaca M37",
        'chapter': Chapters.c12_urban,
        'arc_file': "s102.arc",
        'ap_id': 4861005},
    {'name': "1-2 Red Fruit near Ladder to Old Building Key",
        'chapter': Chapters.c12_urban,
        'arc_file': "s102.arc",
        'ap_id': 4861006},
    {'name': "1-2 Red Fruit below Balcony Emblem",
        'chapter': Chapters.c12_urban,
        'arc_file': "s102.arc",
        'ap_id': 4861007},
    {'name': "1-2 Shotgun Ammo on Shelf Balcony Building F1",
        'chapter': Chapters.c12_urban,
        'arc_file': "s102.arc",
        'ap_id': 4861008},
    {'name': "1-2 Small Gold on Table Balcony Building F1",
        'chapter': Chapters.c12_urban,
        'arc_file': "s102.arc",
        'ap_id': 4861009},
    {'name': "1-2 Large Gold on Table Balcony Building F1",
        'chapter': Chapters.c12_urban,
        'arc_file': "s102.arc",
        'ap_id': 4861010},
    {'name': "1-2 Blonde Girl Ivory Relief",
        'chapter': Chapters.c12_urban,
        'arc_file': "s102.arc",
        'ap_id': 4861011},
    {'name': "1-2 Machinegun Ammo on Table next to Old Building Key",
        'chapter': Chapters.c12_urban,
        'arc_file': "s102.arc",
        'ap_id': 4861012},
    {'name': "1-2 Hand Grenade on Table next to Old Building Key",
        'chapter': Chapters.c12_urban,
        'arc_file': "s102.arc",
        'ap_id': 4861013},
    {'name': "1-2 Furnace Key",
        'chapter': Chapters.c12_furnace,
        'arc_file': "s103.arc",
        'ap_id': 4861014},
    {'name': "1-2 Barrel in Corner of Furnace Room",
        'chapter': Chapters.c12_furnace,
        'arc_file': "s103.arc",
        'ap_id': 4861015},
    {'name': "1-2 Handgun Ammo Briefcase after Furnace Uroboros 1",
        'chapter': Chapters.c12_furnace,
        'arc_file': "s103.arc",
        'ap_id': 4861016},
    {'name': "1-2 Handgun Ammo Briefcase after Furnace Uroboros 2",
        'chapter': Chapters.c12_furnace,
        'arc_file': "s103.arc",
        'ap_id': 4861017},
    {'name': "1-2 Handgun Ammo Briefcase after Furnace Uroboros 3",
        'chapter': Chapters.c12_furnace,
        'arc_file': "s103.arc",
        'ap_id': 4861018},
    {'name': "1-2 Furnace Uroboros Gold Ring",
        'chapter': Chapters.c12_furnace,
        'arc_file': "s103.arc",
        'ap_id': 4861019},
    {'name': "2-1 Green Herb in Shipping Containers",
        'chapter': Chapters.c21_bridge,
        'arc_file': "s104.arc",
        'ap_id': 4861020},
    {'name': "2-1 First Aid in Shipping Container Barrel",
        'chapter': Chapters.c21_bridge,
        'arc_file': "s104.arc",
        'ap_id': 4861021},
    {'name': "2-1 Item near Crossbow Majini",
        'chapter': Chapters.c21_bridge,
        'arc_file': "s104.arc",
        'ap_id': 4861022},
    {'name': "2-1 Box before Bridge Jump", 
        'chapter': Chapters.c21_bridge,
        'arc_file': "s104.arc",
        'ap_id': 4861023},
    {'name': "2-1 Fat Man Jewel Bangle",
        'chapter': Chapters.c21_bridge,
        'arc_file': "s104.arc",
        'ap_id': 4861024},
    {'name': "2-1 Handgun Ammo in First Shanty House 1",
        'chapter': Chapters.c21_shanty,
        'arc_file': "s105.arc",
        'ap_id': 4861025},
    {'name': "2-1 Box on Shanty House 3F",
        'chapter': Chapters.c21_shanty,
        'arc_file': "s105.arc",
        'ap_id': 4861026},
    {'name': "2-1 Green Herb before Chainsaw Majini",
        'chapter': Chapters.c21_shanty,
        'arc_file': "s105.arc",
        'ap_id': 4861027},
    {'name': "2-1 Handgun Ammo in First Shanty House 2",
        'chapter': Chapters.c21_shanty,
        'arc_file': "s105.arc",
        'ap_id': 4861028},
    {'name': "2-1 Box in Shanty Bathroom",
        'chapter': Chapters.c21_shanty,
        'arc_file': "s105.arc",
        'ap_id': 4861029},
    {'name': "2-1 Rifle ammo after BOW Assist Jump", # Sheva Pickup
        'chapter': Chapters.c21_shanty,
        'arc_file': "s105.arc",
        'ap_id': 4861030},
    {'name': "2-1 Handgun Ammo on Shelf in Shanty Main 3F",
        'chapter': Chapters.c21_shanty,
        'arc_file': "s105.arc",
        'ap_id': 4861031},
    {'name': "2-1 Grenade on Balcony in Shanty Main 2F",
        'chapter': Chapters.c21_shanty,
        'arc_file': "s105.arc",
        'ap_id': 4861032},
#    {'name': "",
#        'chapter': Chapters.c21_shanty,
#        'arc_file': "s105.arc",
#        'ap_id': 4861033},
    {'name': "2-1 Grenade on Chair in Shanty Main 2F",
        'chapter': Chapters.c21_shanty,
        'arc_file': "s105.arc",
        'ap_id': 4861034},
    {'name': "2-1 Red Herb on Desk in Shanty Main 1F",
        'chapter': Chapters.c21_shanty,
        'arc_file': "s105.arc",
        'ap_id': 4861035},
    {'name': "2-1 Guard's Key",
        'chapter': Chapters.c21_shanty,
        'arc_file': "s105.arc",
        'ap_id': 4861036},
    {'name': "2-1 Chainsaw Majini Chest 1",
        'chapter': Chapters.c21_shanty,
        'arc_file': "s105.arc",
        'ap_id': 4861037},
#    {'name': "",
#        'chapter': Chapters.c21_shanty,
#        'arc_file': "s105.arc",
#        'ap_id': 4861038},
    {'name': "2-1 Machinegun ammo after BOW Assist Jump", # Sheva Pickup
        'chapter': Chapters.c21_shanty,
        'arc_file': "s105.arc",
        'ap_id': 4861039},
    {'name': "2-1 Chainsaw Majini Chest 3",
        'chapter': Chapters.c21_shanty,
        'arc_file': "s105.arc",
        'ap_id': 4861040},
    {'name': "2-1 Chainsaw Majini Chest 4",
        'chapter': Chapters.c21_shanty,
        'arc_file': "s105.arc",
        'ap_id': 4861041},
#    {'name': "",
#        'chapter': Chapters.c21_shanty,
#        'arc_file': "s105.arc",
#        'ap_id': 4861042},
    {'name': "2-1 Chainsaw Majini Chest 2",
        'chapter': Chapters.c21_shanty,
        'arc_file': "s105.arc",
        'ap_id': 4861043},
    {'name': "2-1 Red Herb from Shanty Bathroom Zombie",
        'chapter': Chapters.c21_shanty,
        'arc_file': "s105.arc",
        'ap_id': 4861044},
#    {'name': "",
#        'chapter': Chapters.c21_shanty,
#        'arc_file': "s105.arc",
#        'ap_id': 4861045},
#    {'name': "",
#        'chapter': Chapters.c21_shanty,
#        'arc_file': "s105.arc",
#        'ap_id': 4861046},
#    {'name': "", # Car level HAHAHA
#        'chapter': Chapters.c23_ndesu,
#        'arc_file': "s111.arc",
#        'ap_id': 4861047},
#    {'name': "", # Car level HAHAHA
#        'chapter': Chapters.c23_ndesu,
#        'arc_file': "s111.arc",
#        'ap_id': 4861048},
    {'name': "2-1 Port Key",
        'chapter': Chapters.c21_port,
        'arc_file': "s113.arc",
        'ap_id': 4861049}, ### Triggered from Herb on Ground outside Shanty Town first building
    {'name': "2-1 Green Herb before Port",
        'chapter': Chapters.c21_port,
        'arc_file': "s113.arc",
        'ap_id': 4861050},
    {'name': "2-1 Barrel inside House before Port",
        'chapter': Chapters.c21_port,
        'arc_file': "s113.arc",
        'ap_id': 4861051},
    {'name': "2-1 Green Herb on Walkway near Boat after Port",
        'chapter': Chapters.c21_port,
        'arc_file': "s113.arc",
        'ap_id': 4861052}, ### Triggered from Item on Shelf in Shanty Town first building
    {'name': "2-1 Green Herb on Table outside S75 building",
        'chapter': Chapters.c21_port,
        'arc_file': "s113.arc",
        'ap_id': 4861053},
    {'name': "2-1 Green Herb on Roof near Port BSAA Emblem",
        'chapter': Chapters.c21_port,
        'arc_file': "s113.arc",
        'ap_id': 4861054}, ### Triggered from Shanty Town Boost Item 2
    {'name': "2-1 Small Gold in Water before Port near Wood",
        'chapter': Chapters.c21_port,
        'arc_file': "s113.arc",
        'ap_id': 4861055},
    {'name': "2-1 Sapphire Pear outside Sewers",
        'chapter': Chapters.c21_port,
        'arc_file': "s113.arc",
        'ap_id': 4861056},
#    {'name': "",
#        'chapter': Chapters.c21_port,
#        'arc_file': "s113.arc",
#        'ap_id': 4861057},
    {'name': "2-1 Small Gold in Water before Port Left Side",
        'chapter': Chapters.c21_port,
        'arc_file': "s113.arc",
        'ap_id': 4861058},
    {'name': "2-1 Large Gold under Boat after Port",
        'chapter': Chapters.c21_port,
        'arc_file': "s113.arc",
        'ap_id': 4861059},
    {'name': "2-1 Topaz Pear under Boat before Port",
        'chapter': Chapters.c21_port,
        'arc_file': "s113.arc",
        'ap_id': 4861060}, ### Registered duplicate location for crate inside the house near the green herb before port
    {'name': "2-1 Market Chest Stall Fruits 1",
        'chapter': Chapters.c21_port,
        'arc_file': "s113.arc",
        'ap_id': 4861061},
    {'name': "2-1 Red Herb on table outside Port Key Building",
        'chapter': Chapters.c21_port,
        'arc_file': "s113.arc",
        'ap_id': 4861062},
    {'name': "2-1 Marquise Ruby inside Market Stall Chest",
        'chapter': Chapters.c21_port,
        'arc_file': "s113.arc",
        'ap_id': 4861063}, ### Triggered from Shanty Town Boost Item 1
    {'name': "2-1 Market Chest Stall Fruits 2",
        'chapter': Chapters.c21_port,
        'arc_file': "s113.arc",
        'ap_id': 4861064}, ### Also triggered off a corpse near the exact same location
    {'name': "2-1 S75 Briefcase",
        'chapter': Chapters.c21_port,
        'arc_file': "s113.arc",
        'ap_id': 4861065},
    {'name': "2-1 Red Fruit inside Port Key Building",
        'chapter': Chapters.c21_port,
        'arc_file': "s113.arc",
        'ap_id': 4861066},
    {'name': "2-1 Jewel Bangle from Fat Man after Port 1",
        'chapter': Chapters.c21_port,
        'arc_file': "s113.arc",
        'ap_id': 4861067},
    {'name': "2-1 Jewel Bangle from Fat Man after Port 2",
        'chapter': Chapters.c21_port,
        'arc_file': "s113.arc",
        'ap_id': 4861068},
    {'name': "2-1 Jewel Bangle from Fat Man after Port 3",
        'chapter': Chapters.c21_port,
        'arc_file': "s113.arc",
        'ap_id': 4861069},
#    {'name': "",
#        'chapter': Chapters.c21_port,
#        'arc_file': "s113.arc",
#        'ap_id': 4861070},
    {'name': "1-1 Executioner's Gold Ring",
        'chapter': Chapters.c11_assembly,
        'arc_file': "s114.arc",
        'ap_id': 4861071},
    {'name': "1-1 VZ61 Briefcase",
        'chapter': Chapters.c11_assembly,
        'arc_file': "s114.arc",
        'ap_id': 4861072},
    {'name': "1-1 Handgun Ammo in Drawer inside Assembly Holdout",
        'chapter': Chapters.c11_assembly,
        'arc_file': "s114.arc",
        'ap_id': 4861073},
#    {'name': "",
#        'chapter': Chapters.c11_assembly,
#        'arc_file': "s114.arc",
#        'ap_id': 4861074},
#    {'name': "",
#        'chapter': Chapters.c11_assembly,
#        'arc_file': "s114.arc",
#        'ap_id': 4861075},
    {'name': "1-1 Red Fruit inside Assembly Holdout",
        'chapter': Chapters.c11_assembly,
        'arc_file': "s114.arc",
        'ap_id': 4861076},
    {'name': "1-1 Box in back of Assembly Holdout",
        'chapter': Chapters.c11_assembly,
        'arc_file': "s114.arc",
        'ap_id': 4861077},
    {'name': "1-1 Box above Assembly Holdout",
        'chapter': Chapters.c11_assembly,
        'arc_file': "s114.arc",
        'ap_id': 4861078},
#    {'name': "",
#        'chapter': Chapters.c11_assembly,
#        'arc_file': "s114.arc",
#        'ap_id': 4861079},
    {'name': "1-1 Barrel in Sewer after Assembly",
        'chapter': Chapters.c11_assembly,
        'arc_file': "s114.arc",
        'ap_id': 4861080},
    {'name': "1-1 Green Fruit near Assembly Gate",
        'chapter': Chapters.c11_assembly,
        'arc_file': "s114.arc",
        'ap_id': 4861081},
    {'name': "1-1 Green Fruit inside Assembly Holdout",
        'chapter': Chapters.c11_assembly,
        'arc_file': "s114.arc",
        'ap_id': 4861082},
#    {'name': "",
#        'chapter': Chapters.c11_assembly,
#        'arc_file': "s114.arc",
#        'ap_id': 4861083},
    {'name': "1-1 Handgun Ammo next to TV inside Assembly Holdout",
        'chapter': Chapters.c11_assembly,
        'arc_file': "s114.arc",
        'ap_id': 4861084},
#    {'name': "",
#        'chapter': Chapters.c11_assembly,
#        'arc_file': "s114.arc",
#        'ap_id': 4861085},
#    {'name': "",
#        'chapter': Chapters.c11_assembly,
#        'arc_file': "s114.arc",
#        'ap_id': 4861086},
    {'name': "1-1 Handgun Ammo before Assembly Cutscene",
        'chapter': Chapters.c11_assembly,
        'arc_file': "s114.arc",
        'ap_id': 4861087},
#    {'name': "",
#        'chapter': Chapters.c11_assembly,
#        'arc_file': "s114.arc",
#        'ap_id': 4861088},
#    {'name': "",
#        'chapter': Chapters.c11_assembly,
#        'arc_file': "s114.arc",
#        'ap_id': 4861089},
#    {'name': "",
#        'chapter': Chapters.c11_assembly,
#        'arc_file': "s114.arc",
#        'ap_id': 4861090},
#    {'name': "",
#        'chapter': Chapters.c11_assembly,
#        'arc_file': "s114.arc",
#        'ap_id': 4861091},
    {'name': "1-1 Green Herb before Assembly Cutscene",
        'chapter': Chapters.c11_assembly,
        'arc_file': "s114.arc",
        'ap_id': 4861092},
#    {'name': "",
#        'chapter': Chapters.c11_assembly,
#        'arc_file': "s114.arc",
#        'ap_id': 4861093},
#    {'name': "",
#        'chapter': Chapters.c11_assembly,
#        'arc_file': "s114.arc",
#        'ap_id': 4861094},
#    {'name': "",
#        'chapter': Chapters.c11_assembly,
#        'arc_file': "s114.arc",
#        'ap_id': 4861095},
#    {'name': "",
#        'chapter': Chapters.c11_assembly,
#        'arc_file': "s114.arc",
#        'ap_id': 4861096},
#    {'name': "",
#        'chapter': Chapters.c11_assembly,
#        'arc_file': "s114.arc",
#        'ap_id': 4861097},
#    {'name': "",
#        'chapter': Chapters.c11_assembly,
#        'arc_file': "s114.arc",
#        'ap_id': 4861098},
    {'name': "1-2 Barrel near Assembly Gate",
        'chapter': Chapters.c11_assembly,
        'arc_file': "s114.arc",
        'ap_id': 4861099},
    {'name': "1-1 Green Herb on Shelf near Deer Carcass",
        'chapter': Chapters.c11_alley1,
        'arc_file': "s115.arc",
        'ap_id': 4861100},
    {'name': "1-1 Box in Butcher Shop",
        'chapter': Chapters.c11_alley1,
        'arc_file': "s115.arc",
        'ap_id': 4861101},
    {'name': "1-1 Barrel near Deer Carcass",
        'chapter': Chapters.c11_alley1,
        'arc_file': "s115.arc",
        'ap_id': 4861102},
    {'name': "1-1 Box near Deer Carcass 2",
        'chapter': Chapters.c11_alley1,
        'arc_file': "s115.arc",
        'ap_id': 4861103},
#    {'name': "",
#        'chapter': Chapters.c11_alley1,
#        'arc_file': "s115.arc",
#        'ap_id': 4861104},
    {'name': "1-1 Box near Deer Carcass 1",
        'chapter': Chapters.c11_alley1,
        'arc_file': "s115.arc",
        'ap_id': 4861105},
    {'name': "1-1 M92F Handgun Briefcase 1",
        'chapter': Chapters.c11_checkpoint,
        'arc_file': "s115.arc",
        'ap_id': 4861106},
    {'name': "1-1 M92F Handgun Briefcase 2", # Potentially missable, as you can only grab one at a time. Requires either a reload to grab the other, or by discarding the first one, then grabbing the second one before triggering the cutscene.
        'chapter': Chapters.c11_checkpoint,
        'arc_file': "s115.arc",
        'ap_id': 4861107},
    {'name': "1-1 Barrel outside Butcher Shop",
        'chapter': Chapters.c11_alley1,
        'arc_file': "s115.arc",
        'ap_id': 4861108},
#    {'name': "",
#        'chapter': Chapters.c11_alley1,
#        'arc_file': "s115.arc",
#        'ap_id': 4861109},
#    {'name': "",
#        'chapter': Chapters.c11_alley1,
#        'arc_file': "s115.arc",
#        'ap_id': 4861110},
    {'name': "1-1 Handgun Ammo before Assembly 1",
        'chapter': Chapters.c11_alley2,
        'arc_file': "s116.arc",
        'ap_id': 4861111},
    {'name': "1-1 Handgun Ammo after Ambush",
        'chapter': Chapters.c11_alley2,
        'arc_file': "s116.arc",
        'ap_id': 4861112},
    {'name': "1-1 Green Herb before Assembly",
        'chapter': Chapters.c11_alley2,
        'arc_file': "s116.arc",
        'ap_id': 4861113},
    {'name': "1-1 Red Herb on Shelf after Ambush",
        'chapter': Chapters.c11_alley2,
        'arc_file': "s116.arc",
        'ap_id': 4861114},
    {'name': "1-1 Handgun Ammo before Assembly 2",
        'chapter': Chapters.c11_alley2,
        'arc_file': "s116.arc",
        'ap_id': 4861115},
#    {'name': "",
#        'chapter': Chapters.c11_alley2,
#        'arc_file': "s116.arc",
#        'ap_id': 4861116},
#    {'name': "",
#        'chapter': Chapters.c11_alley2,
#        'arc_file': "s116.arc",
#        'ap_id': 4861117},
    {'name': "1-1 Handgun Ammo after First Zombie",
        'chapter': Chapters.c11_alley2,
        'arc_file': "s116.arc",
        'ap_id': 4861118},
#    {'name': "",
#        'chapter': Chapters.c11_alley2,
#        'arc_file': "s116.arc",
#        'ap_id': 4861119},
#    {'name': "",
#        'chapter': Chapters.c11_alley2,
#        'arc_file': "s116.arc",
#        'ap_id': 4861120},
    {'name': "1-2 Handgun Ammo from Alpha Team", 
        'chapter': Chapters.c12_abandoned,
        'arc_file': "s117.arc",
        'ap_id': 4861121},
    {'name': "1-2 Chest beneath Water Tower Emblem 1",
        'chapter': Chapters.c12_abandoned,
        'arc_file': "s117.arc",
        'ap_id': 4861122},
    {'name': "1-2 Chest beneath Water Tower Emblem 2",
        'chapter': Chapters.c12_abandoned,
        'arc_file': "s117.arc",
        'ap_id': 4861123},
    {'name': "1-2 Chest beneath Water Tower Emblem 3",
        'chapter': Chapters.c12_abandoned,
        'arc_file': "s117.arc",
        'ap_id': 4861124},
    {'name': "2-1 Storage Garage Chest 1",
        'chapter': Chapters.c21_storage,
        'arc_file': "s118.arc",
        'ap_id': 4861125},
    {'name': "2-1 Storage Garage Chest 22",
        'chapter': Chapters.c21_storage,
        'arc_file': "s118.arc",
        'ap_id': 4861126},
    {'name': "2-1 Storage Garage Chest 3",
        'chapter': Chapters.c21_storage,
        'arc_file': "s118.arc",
        'ap_id': 4861127},
    {'name': "2-1 H&K MP5 Briefcase",
        'chapter': Chapters.c21_storage,
        'arc_file': "s118.arc",
        'ap_id': 4861128},
#    {'name': "", # Object Spawns or BSAA Emblems, Ignore these
#        'chapter': Chapters.c21_storage,
#        'arc_file': "s118.arc",
#        'ap_id': 4861129},
#    {'name': "", # Object Spawns or BSAA Emblems, Ignore these
#        'chapter': Chapters.c21_storage,
#        'arc_file': "s118.arc",
#        'ap_id': 4861130},
#    {'name': "", # Object Spawns or BSAA Emblems, Ignore these
#        'chapter': Chapters.c21_storage,
#        'arc_file': "s118.arc",
#        'ap_id': 4861131},
#    {'name': "", # Object Spawns or BSAA Emblems, Ignore these
#        'chapter': Chapters.c22_station,
#        'arc_file': "s119.arc",
#        'ap_id': 4861132},
    {'name': "2-2 Gold on Table at Level Start",
        'chapter': Chapters.c22_station,
        'arc_file': "s119.arc",
        'ap_id': 4861133},
    {'name': "2-2 Handgun Ammo on Table at Level Start",
        'chapter': Chapters.c22_station,
        'arc_file': "s119.arc",
        'ap_id': 4861134},
    {'name': "2-2 Machinegun Ammo on Fence past Train",
        'chapter': Chapters.c22_station,
        'arc_file': "s119.arc",
        'ap_id': 4861135},
    {'name': "2-2 Jewel Beetle on Train Car",
        'chapter': Chapters.c22_station,
        'arc_file': "s119.arc",
        'ap_id': 4861136},
    {'name': "2-2 Large Gold on Minecart",
        'chapter': Chapters.c22_station,
        'arc_file': "s119.arc",
        'ap_id': 4861137},
    {'name': "2-2 Large Gold on top of Train",
        'chapter': Chapters.c22_station,
        'arc_file': "s119.arc",
        'ap_id': 4861138},
#    {'name': "",
#        'chapter': Chapters.c22_station,
#        'arc_file': "s119.arc",
#        'ap_id': 4861139},
#    {'name': "",
#        'chapter': Chapters.c22_station,
#        'arc_file': "s119.arc",
#        'ap_id': 4861140},
#    {'name': "",
#        'chapter': Chapters.c31_marsh,
#        'arc_file': "s200.arc",
#        'ap_id': 4861141},
#    {'name': "",
#        'chapter': Chapters.c31_marsh,
#        'arc_file': "s200.arc",
#        'ap_id': 4861142},
    {'name': "3-1 Shaman Slate",
        'chapter': Chapters.c31_marsh,
        'arc_file': "s200.arc",
        'ap_id': 4861143},
    {'name': "3-1 Raptor Slate",
        'chapter': Chapters.c31_marsh,
        'arc_file': "s200.arc",
        'ap_id': 4861144},
    {'name': "3-1 Silver Idol on SW Island",
        'chapter': Chapters.c31_marsh,
        'arc_file': "s200.arc",
        'ap_id': 4861145},
    {'name': "3-1 Silver Idol on NE Island", # Sheva Pickup
        'chapter': Chapters.c31_marsh,
        'arc_file': "s200.arc",
        'ap_id': 4861146},
    {'name': "3-1 Silver Chalice on Central Island",
        'chapter': Chapters.c31_marsh,
        'arc_file': "s200.arc",
        'ap_id': 4861147},
    {'name': "3-1 Ruby Pear near Alligators",
        'chapter': Chapters.c31_marsh,
        'arc_file': "s200.arc",
        'ap_id': 4861148},
    {'name': "3-1 Brown Beetle on Central Island",
        'chapter': Chapters.c31_marsh,
        'arc_file': "s200.arc",
        'ap_id': 4861149},
    {'name': "3-1 Silver Chalice near NW Island Emblem",
        'chapter': Chapters.c31_marsh,
        'arc_file': "s200.arc",
        'ap_id': 4861150},
    {'name': "3-1 Slate Map",
        'chapter': Chapters.c31_marsh,
        'arc_file': "s200.arc",
        'ap_id': 4861151},
#    {'name': "",
#        'chapter': Chapters.c31_marsh,
#        'arc_file': "s200.arc",
#        'ap_id': 4861152},
#    {'name': "",
#        'chapter': Chapters.c31_marsh,
#        'arc_file': "s200.arc",
#        'ap_id': 4861153},
#    {'name': "",
#        'chapter': Chapters.c31_marsh,
#        'arc_file': "s200.arc",
#        'ap_id': 4861154},
    {'name': "3-1 Green Herb on Shelf on SW Island",
        'chapter': Chapters.c31_marsh,
        'arc_file': "s200.arc",
        'ap_id': 4861155},
#    {'name': "",
#        'chapter': Chapters.c31_marsh,
#        'arc_file': "s200.arc",
#        'ap_id': 4861156},
    {'name': "3-1 Warrior Slate",
        'chapter': Chapters.c31_marsh,
        'arc_file': "s200.arc",
        'ap_id': 4861157},
#    {'name': "",
#        'chapter': Chapters.c31_marsh,
#        'arc_file': "s200.arc",
#        'ap_id': 4861158},
    {'name': "3-1 Beast Slate",
        'chapter': Chapters.c31_marsh,
        'arc_file': "s200.arc",
        'ap_id': 4861159},
    {'name': "3-1 Red Herb on Shelf on East Island",
        'chapter': Chapters.c31_marsh,
        'arc_file': "s200.arc",
        'ap_id': 4861160},
    {'name': "3-1 Brown Beetle on Tree near NE Island",
        'chapter': Chapters.c31_marsh,
        'arc_file': "s200.arc",
        'ap_id': 4861161},
    {'name': "3-1 White Egg on Shelf on Central Island",
        'chapter': Chapters.c31_marsh,
        'arc_file': "s200.arc",
        'ap_id': 4861162},
    {'name': "3-1 White Egg in Pen on Central Island",
        'chapter': Chapters.c31_marsh,
        'arc_file': "s200.arc",
        'ap_id': 4861163},
    {'name': "3-1 White Egg on Shelf on East Island",
        'chapter': Chapters.c31_marsh,
        'arc_file': "s200.arc",
        'ap_id': 4861164},
#    {'name': "",
#        'chapter': Chapters.c31_marsh,
#        'arc_file': "s200.arc",
#        'ap_id': 4861165},
    {'name': "3-1 Brown Beetle near Beast Slate",
        'chapter': Chapters.c31_marsh,
        'arc_file': "s200.arc",
        'ap_id': 4861166},
    {'name': "3-1 Brown Beetle on Tree near SW Island",
        'chapter': Chapters.c31_marsh,
        'arc_file': "s200.arc",
        'ap_id': 4861167},
    {'name': "3-1 Brown Beetle on Shipwreck",
        'chapter': Chapters.c31_marsh,
        'arc_file': "s200.arc",
        'ap_id': 4861168},
#    {'name': "",
#        'chapter': Chapters.c31_marsh,
#        'arc_file': "s200.arc",
#        'ap_id': 4861169},
    {'name': "3-1 Emerald Pear in Mask on NE Island",
        'chapter': Chapters.c31_marsh,
        'arc_file': "s200.arc",
        'ap_id': 4861170},
#    {'name': "",
#        'chapter': Chapters.c31_marsh,
#        'arc_file': "s200.arc",
#        'ap_id': 4861171},
    {'name': "3-1 Rocket Launcher Briefcase",
        'chapter': Chapters.c31_marsh,
        'arc_file': "s200.arc",
        'ap_id': 4861172},
    {'name': "3-1 Brown Beetle in Water near NW Island Emblem",
        'chapter': Chapters.c31_marsh,
        'arc_file': "s200.arc",
        'ap_id': 4861173},
#    {'name': "",
#        'chapter': Chapters.c31_marsh,
#        'arc_file': "s200.arc",
#        'ap_id': 4861174},
#    {'name': "",
#        'chapter': Chapters.c31_marsh,
#        'arc_file': "s200.arc",
#        'ap_id': 4861175},
#    {'name': "",
#        'chapter': Chapters.c31_marsh,
#        'arc_file': "s200.arc",
#        'ap_id': 4861176},
#    {'name': "",
#        'chapter': Chapters.c31_marsh,
#        'arc_file': "s200.arc",
#        'ap_id': 4861177},
#    {'name': "",
#        'chapter': Chapters.c31_marsh,
#        'arc_file': "s200.arc",
#        'ap_id': 4861178},
#    {'name': "",
#        'chapter': Chapters.c31_marsh,
#        'arc_file': "s200.arc",
#        'ap_id': 4861179},
#    {'name': "",
#        'chapter': Chapters.c31_marsh,
#        'arc_file': "s200.arc",
#        'ap_id': 4861180},
    {'name': "3-1 Ruby Pear near Beast Slate",
        'chapter': Chapters.c31_marsh,
        'arc_file': "s200.arc",
        'ap_id': 4861181},
#    {'name': "",
#        'chapter': Chapters.c32_exegrounds,
#        'arc_file': "s201.arc",
#        'ap_id': 4861182},
#    {'name': "",
#        'chapter': Chapters.c32_exegrounds,
#        'arc_file': "s201.arc",
#        'ap_id': 4861183},
#    {'name': "",
#        'chapter': Chapters.c32_exegrounds,
#        'arc_file': "s201.arc",
#        'ap_id': 4861184},
    {'name': "3-2 First Aid in Vase",
        'chapter': Chapters.c32_exegrounds,
        'arc_file': "s201.arc",
        'ap_id': 4861185},
#    {'name': "",
#        'chapter': Chapters.c32_exegrounds,
#        'arc_file': "s201.arc",
#        'ap_id': 4861186},
#    {'name': "",
#        'chapter': Chapters.c32_exegrounds,
#        'arc_file': "s201.arc",
#        'ap_id': 4861187},
    {'name': "3-1 Sapphire Square in Grass near Tricell Tents",
        'chapter': Chapters.c32_exegrounds,
        'arc_file': "s201.arc",
        'ap_id': 4861188},
#    {'name': "",
#        'chapter': Chapters.c32_exegrounds,
#        'arc_file': "s201.arc",
##        'ap_id': 4861189},
#    {'name': "",
#        'chapter': Chapters.c32_exegrounds,
#        'arc_file': "s201.arc",
#        'ap_id': 4861190},
    {'name': "3-1 Item on Oil Barrels near Tricell Tents",
        'chapter': Chapters.c32_exegrounds,
        'arc_file': "s201.arc",
        'ap_id': 4861191},
    {'name': "3-1 Jewel Beetle on Cliff near Tricell Tents",
        'chapter': Chapters.c32_exegrounds,
        'arc_file': "s201.arc",
        'ap_id': 4861192},
#    {'name': "",
#        'chapter': Chapters.c32_exegrounds,
#        'arc_file': "s201.arc",
#        'ap_id': 4861193},
#    {'name': "",
#        'chapter': Chapters.c32_exegrounds,
#        'arc_file': "s201.arc",
#        'ap_id': 4861194},
    {'name': "3-1 Handgun Ammo in Ladder Building 1",
        'chapter': Chapters.c31_village,
        'arc_file': "s202.arc",
        'ap_id': 4861195},
#    {'name': "",
#        'chapter': Chapters.c31_village,
#        'arc_file': "s202.arc",
#        'ap_id': 4861196},
#    {'name': "",
#        'chapter': Chapters.c31_village,
#        'arc_file': "s202.arc",
#        'ap_id': 4861197},
    {'name': "3-1 Green Herb on Shelf past Bridge",
        'chapter': Chapters.c31_village,
        'arc_file': "s202.arc",
        'ap_id': 4861198},
    {'name': "3-1 Green Herb in Ladder Building 1",
        'chapter': Chapters.c31_village,
        'arc_file': "s202.arc",
        'ap_id': 4861199},
#    {'name': "",
#        'chapter': Chapters.c31_village,
#        'arc_file': "s202.arc",
#        'ap_id': 4861200},
    {'name': "3-1 Ceremonial Mask in Cave past Bridge",
        'chapter': Chapters.c31_village,
        'arc_file': "s202.arc",
        'ap_id': 4861201},
    {'name': "3-1 Small Gold on Shelf past Bridge",
        'chapter': Chapters.c31_village,
        'arc_file': "s202.arc",
        'ap_id': 4861202},
#    {'name': "",
#        'chapter': Chapters.c31_village,
#        'arc_file': "s202.arc",
#        'ap_id': 4861203},
#    {'name': "",
#        'chapter': Chapters.c31_village,
#        'arc_file': "s202.arc",
#        'ap_id': 4861204},
    {'name': "3-1 Handgun Ammo in Ladder Building 2",
        'chapter': Chapters.c31_village,
        'arc_file': "s202.arc",
        'ap_id': 4861205},
    {'name': "3-1 Magnum Ammo on Shelf past Bridge",
        'chapter': Chapters.c31_village,
        'arc_file': "s202.arc",
        'ap_id': 4861206},
    {'name': "3-1 S&W M29",
        'chapter': Chapters.c31_village,
        'arc_file': "s202.arc",
        'ap_id': 4861207},
#    {'name': "",
#        'chapter': Chapters.c31_village,
#        'arc_file': "s202.arc",
#        'ap_id': 4861208},
    {'name': "3-1 Giant Majini Blue Enigma 1",
        'chapter': Chapters.c31_village,
        'arc_file': "s202.arc",
        'ap_id': 4861209},
    {'name': "3-1 Giant Majini Blue Enigma 2",
        'chapter': Chapters.c31_village,
        'arc_file': "s202.arc",
        'ap_id': 4861210},
#    {'name': "",
#        'chapter': Chapters.c31_village,
#        'arc_file': "s202.arc",
#        'ap_id': 4861211},
#    {'name': "",
#        'chapter': Chapters.c31_village,
#        'arc_file': "s202.arc",
#        'ap_id': 4861212},
#    {'name': "",
#        'chapter': Chapters.c31_village,
#        'arc_file': "s202.arc",
#        'ap_id': 4861213},
#    {'name': "",
#        'chapter': Chapters.c31_village,
#        'arc_file': "s202.arc",
#        'ap_id': 4861214},
    {'name': "3-1 Proximity Mine near Josh",
        'chapter': Chapters.c32_control,
        'arc_file': "s203.arc",
        'ap_id': 4861215},
#    {'name': "",
#        'chapter': Chapters.c32_control,
#        'arc_file': "s203.arc",
#        'ap_id': 4861216},
#    {'name': "",
#        'chapter': Chapters.c32_control,
#        'arc_file': "s203.arc",
#        'ap_id': 4861217},
#    {'name': "",
#        'chapter': Chapters.c32_control,
#        'arc_file': "s203.arc",
#        'ap_id': 4861218},
    {'name': "3-2 Fat Man Jewel Bangle",
        'chapter': Chapters.c32_control,
        'arc_file': "s203.arc",
        'ap_id': 4861219},
#    {'name': "",
#        'chapter': Chapters.c32_control,
#        'arc_file': "s203.arc",
#        'ap_id': 4861220},
#    {'name': "",
#        'chapter': Chapters.c32_control,
#        'arc_file': "s203.arc",
#        'ap_id': 4861221},
#    {'name': "",
#        'chapter': Chapters.c32_control,
#        'arc_file': "s203.arc",
#        'ap_id': 4861222},
    {'name': "3-3 Marquise Emerald in Drawer at Second Checkpoint",
        'chapter': Chapters.c33_oilboat,
        'arc_file': "s204.arc",
        'ap_id': 4861223},
    {'name': "3-3 Supply Desk near M3 Briefcase 1",
        'chapter': Chapters.c33_oilboat,
        'arc_file': "s204.arc",
        'ap_id': 4861224},
    {'name': "3-3 Supply Desk near M3 Briefcase 2",
        'chapter': Chapters.c33_oilboat,
        'arc_file': "s204.arc",
        'ap_id': 4861225},
    {'name': "3-3 Supply Desk near M3 Briefcase 3",
        'chapter': Chapters.c33_oilboat,
        'arc_file': "s204.arc",
        'ap_id': 4861226},
    {'name': "3-3 Supply Desk near M3 Briefcase 4",
        'chapter': Chapters.c33_oilboat,
        'arc_file': "s204.arc",
        'ap_id': 4861227},
    {'name': "3-3 M3 Briefcase",
        'chapter': Chapters.c33_oilboat,
        'arc_file': "s204.arc",
        'ap_id': 4861228},
#    {'name': "",
#        'chapter': Chapters.c33_oilboat,
#        'arc_file': "s204.arc",
#        'ap_id': 4861229},
    {'name': "3-3 Green Herb near Boat at Second Checkpoint",
        'chapter': Chapters.c33_oilboat,
        'arc_file': "s204.arc",
        'ap_id': 4861230},
    {'name': "3-3 Green Herb near Turrets at Second Checkpoint",
        'chapter': Chapters.c33_oilboat,
        'arc_file': "s204.arc",
        'ap_id': 4861231},
    {'name': "3-3 Red Herb near Boat at Second Checkpoint",
        'chapter': Chapters.c33_oilboat,
        'arc_file': "s204.arc",
        'ap_id': 4861232},
    {'name': "3-3 Handgun Ammo at Second Checkpoint",
        'chapter': Chapters.c33_oilboat,
        'arc_file': "s204.arc",
        'ap_id': 4861233},
    {'name': "3-3 Rifle Ammo at Second Checkpoint",
        'chapter': Chapters.c33_oilboat,
        'arc_file': "s204.arc",
        'ap_id': 4861234},
#    {'name': "",
#        'chapter': Chapters.c33_oilboat,
#        'arc_file': "s204.arc",
#        'ap_id': 4861235},
    {'name': "3-3 Machinegun Ammo below Right Ladder at Second Checkpoint",
        'chapter': Chapters.c33_oilboat,
        'arc_file': "s204.arc",
        'ap_id': 4861236},
#    {'name': "",
#        'chapter': Chapters.c33_oilboat,
#        'arc_file': "s204.arc",
#        'ap_id': 4861237},
#    {'name': "",
#        'chapter': Chapters.c33_oilboat,
#        'arc_file': "s204.arc",
#        'ap_id': 4861238},
    {'name': "3-3 Handgun Ammo at First Checkpoint",
        'chapter': Chapters.c33_oilboat,
        'arc_file': "s204.arc",
        'ap_id': 4861239},
    {'name': "3-3 First Aid at Irving",
        'chapter': Chapters.c33_irving,
        'arc_file': "s205.arc",
        'ap_id': 4861240},
#    {'name': "",
#        'chapter': Chapters.c32_refinery,
#        'arc_file': "s207.arc",
#        'ap_id': 4861241},
    {'name': "3-2 Proximity Mine",
        'chapter': Chapters.c32_refinery,
        'arc_file': "s207.arc",
        'ap_id': 4861242},
    {'name': "3-2 Chainsaw Majini Venom Fang 1",
        'chapter': Chapters.c32_refinery,
        'arc_file': "s207.arc",
        'ap_id': 4861243},
    {'name': "3-2 Chainsaw Majini Venom Fang 2",
        'chapter': Chapters.c32_refinery,
        'arc_file': "s207.arc",
        'ap_id': 4861244},
#    {'name': "",
#        'chapter': Chapters.c32_refinery,
#        'arc_file': "s207.arc",
#        'ap_id': 4861245},
    {'name': "3-2 Hand Grenade Barrel on Docks",
        'chapter': Chapters.c32_docks,
        'arc_file': "s209.arc",
        'ap_id': 4861246},
    {'name': "3-2 Fat Man Gold Ring on Docks",
        'chapter': Chapters.c32_docks,
        'arc_file': "s209.arc",
        'ap_id': 4861247},
    {'name': "3-2 Gold on Docks",
        'chapter': Chapters.c32_docks,
        'arc_file': "s209.arc",
        'ap_id': 4861248},
    {'name': "4-1 Trap Sarcophagus East",
        'chapter': Chapters.c41_ancient,
        'arc_file': "s300.arc",
        'ap_id': 4861249},
    {'name': "4-1 Trap Sarcophagus West",
        'chapter': Chapters.c41_ancient,
        'arc_file': "s300.arc",
        'ap_id': 4861250},
    {'name': "4-1 Trap Sarcophagus South",
        'chapter': Chapters.c41_ancient,
        'arc_file': "s300.arc",
        'ap_id': 4861251},
    {'name': "4-1 Ruby Pear above Archway before Dropping",
        'chapter': Chapters.c41_ancient,
        'arc_file': "s300.arc",
        'ap_id': 4861252},
#    {'name': "",
#        'chapter': Chapters.c41_ancient,
#        'arc_file': "s300.arc",
#        'ap_id': 4861253},
#    {'name': "",
#        'chapter': Chapters.c41_ancient,
#        'arc_file': "s300.arc",
#        'ap_id': 4861254},
#    {'name': "",
#        'chapter': Chapters.c41_ancient,
#        'arc_file': "s300.arc",
#        'ap_id': 4861255},
    {'name': "4-1 Second Sarcophagus 4",
        'chapter': Chapters.c41_ancient,
        'arc_file': "s300.arc",
        'ap_id': 4861256},
    {'name': "4-1 Second Sarcophagus 5",
        'chapter': Chapters.c41_ancient,
        'arc_file': "s300.arc",
        'ap_id': 4861257},
    {'name': "4-1 Second Sarcophagus 6",
        'chapter': Chapters.c41_ancient,
        'arc_file': "s300.arc",
        'ap_id': 4861258},
#    {'name': "",
#        'chapter': Chapters.c41_ancient,
#        'arc_file': "s300.arc",
#        'ap_id': 4861259},
    {'name': "4-1 Second Sarcophagus 3",
        'chapter': Chapters.c41_ancient,
        'arc_file': "s300.arc",
        'ap_id': 4861260},
    {'name': "4-1 Green Herb below Collapsing Bridge",
        'chapter': Chapters.c41_ancient,
        'arc_file': "s300.arc",
        'ap_id': 4861261},
#    {'name': "",
#        'chapter': Chapters.c41_ancient,
#        'arc_file': "s300.arc",
#        'ap_id': 4861262},
    {'name': "4-1 Red Herb on Stairs after Collapsing Bridge",
        'chapter': Chapters.c41_ancient,
        'arc_file': "s300.arc",
        'ap_id': 4861263},
    {'name': "4-1 Second Sarcophagus 2",
        'chapter': Chapters.c41_ancient,
        'arc_file': "s300.arc",
        'ap_id': 4861264},
    {'name': "4-1 Second Sarcophagus 7",
        'chapter': Chapters.c41_ancient,
        'arc_file': "s300.arc",
        'ap_id': 4861265},
    {'name': "4-1 Second Sarcophagus 1",
        'chapter': Chapters.c41_ancient,
        'arc_file': "s300.arc",
        'ap_id': 4861266},
    {'name': "4-1 Emerald Pear in Torch before Collapsing Bridge",
        'chapter': Chapters.c41_ancient,
        'arc_file': "s300.arc",
        'ap_id': 4861267},
    {'name': "4-1 Sapphire in Torch behind Second Sarcophagus Room",
        'chapter': Chapters.c41_ancient,
        'arc_file': "s300.arc",
        'ap_id': 4861268},
    {'name': "4-1 Topaz Pear on Stairs after Collapsing Bridge",
        'chapter': Chapters.c41_ancient,
        'arc_file': "s300.arc",
        'ap_id': 4861269},
    {'name': "4-1 Mummy holding a Ruby Pear",
        'chapter': Chapters.c41_ancient,
        'arc_file': "s300.arc",
        'ap_id': 4861270},
    {'name': "4-1 First Sarcophagus 1",
        'chapter': Chapters.c41_ancient,
        'arc_file': "s300.arc",
        'ap_id': 4861271},
    {'name': "4-1 First Sarcophagus 2",
        'chapter': Chapters.c41_ancient,
        'arc_file': "s300.arc",
        'ap_id': 4861272},
    {'name': "4-1 First Sarcophagus 3",
        'chapter': Chapters.c41_ancient,
        'arc_file': "s300.arc",
        'ap_id': 4861273},
    {'name': "4-1 First Sarcophagus 4",
        'chapter': Chapters.c41_ancient,
        'arc_file': "s300.arc",
        'ap_id': 4861274},
    {'name': "4-1 First Sarcophagus 5",
        'chapter': Chapters.c41_ancient,
        'arc_file': "s300.arc",
        'ap_id': 4861275},
    {'name': "4-1 First Sarcophagus 6",
        'chapter': Chapters.c41_ancient,
        'arc_file': "s300.arc",
        'ap_id': 4861276},
    {'name': "4-1 First Sarcophagus 7",
        'chapter': Chapters.c41_ancient,
        'arc_file': "s300.arc",
        'ap_id': 4861277},
    {'name': "4-1 Ruby Oval Red Statue",
        'chapter': Chapters.c41_labyrinth,
        'arc_file': "s301.arc",
        'ap_id': 4861278},
#    {'name': "",
#        'chapter': Chapters.c41_labyrinth,
#        'arc_file': "s301.arc",
#        'ap_id': 4861279},
    {'name': "4-1 Flash Rounds Chest 1",
        'chapter': Chapters.c41_labyrinth,
        'arc_file': "s301.arc",
        'ap_id': 4861280},
    {'name': "4-1 Sapphire Square Blue Statue",
        'chapter': Chapters.c41_labyrinth,
        'arc_file': "s301.arc",
        'ap_id': 4861281},
#    {'name': "",
#        'chapter': Chapters.c41_labyrinth,
#        'arc_file': "s301.arc",
#        'ap_id': 4861282},
    {'name': "4-1 Gold Idol beside Green Statue",
        'chapter': Chapters.c41_labyrinth,
        'arc_file': "s301.arc",
        'ap_id': 4861283},
    {'name': "4-1 Popokarimu Soul Heart",
        'chapter': Chapters.c41_labyrinth,
        'arc_file': "s301.arc",
        'ap_id': 4861284},
    {'name': "4-1 Topaz Square on Labyrinth 3F Ceiling",
        'chapter': Chapters.c41_labyrinth,
        'arc_file': "s301.arc",
        'ap_id': 4861285},
    {'name': "4-1 Emerald Square Green Statue", 
        'chapter': Chapters.c41_labyrinth,
        'arc_file': "s301.arc",
        'ap_id': 4861286},
    {'name': "4-1 Topaz Square Gold Statue", 
        'chapter': Chapters.c41_labyrinth,
        'arc_file': "s301.arc",
        'ap_id': 4861287},
    {'name': "4-1 Ruby Pear Purple Statue Lower",
        'chapter': Chapters.c41_labyrinth,
        'arc_file': "s301.arc",
        'ap_id': 4861288},
    {'name': "4-1 Sapphire Pear Purple Statue Upper",
        'chapter': Chapters.c41_labyrinth,
        'arc_file': "s301.arc",
        'ap_id': 4861289},
#    {'name': "",
#        'chapter': Chapters.c41_labyrinth,
#        'arc_file': "s301.arc",
#        'ap_id': 4861290},
    {'name': "4-1 M40 GL Briefcase",
        'chapter': Chapters.c41_labyrinth,
        'arc_file': "s301.arc",
        'ap_id': 4861291},
    {'name': "4-1 Flash Rounds Chest 2",
        'chapter': Chapters.c41_labyrinth,
        'arc_file': "s301.arc",
        'ap_id': 4861292},
    {'name': "4-2 Sky Emblem",
        'chapter': Chapters.c42_worship,
        'arc_file': "s302.arc",
        'ap_id': 4861293},
    {'name': "4-2 Earth Emblem",
        'chapter': Chapters.c42_worship,
        'arc_file': "s302.arc",
        'ap_id': 4861294},
    {'name': "4-2 Sea Emblem",
        'chapter': Chapters.c42_worship,
        'arc_file': "s302.arc",
        'ap_id': 4861295},
#    {'name': "",
#        'chapter': Chapters.c42_worship,
#        'arc_file': "s302.arc",
#        'ap_id': 4861296},
#    {'name': "",
#        'chapter': Chapters.c42_worship,
#        'arc_file': "s302.arc",
#        'ap_id': 4861297},
#    {'name': "",
#        'chapter': Chapters.c42_worship,
#        'arc_file': "s302.arc",
#        'ap_id': 4861298},
    {'name': "4-1 Hand Grenade in Vase at Start",
        'chapter': Chapters.c42_worship,
        'arc_file': "s302.arc",
        'ap_id': 4861299},
    {'name': "4-2 Green Herb near Sky Emblem 1",
        'chapter': Chapters.c42_worship,
        'arc_file': "s302.arc",
        'ap_id': 4861300},
#    {'name': "",
#        'chapter': Chapters.c42_worship,
#        'arc_file': "s302.arc",
#        'ap_id': 4861301},
    {'name': "4-2 Green Herb near Earth Emblem",
        'chapter': Chapters.c42_worship,
        'arc_file': "s302.arc",
        'ap_id': 4861302},
#    {'name': "",
#        'chapter': Chapters.c42_worship,
#        'arc_file': "s302.arc",
#        'ap_id': 4861303},
    {'name': "4-2 Giant Majini Blue Enigma near Sky Emblem",
        'chapter': Chapters.c42_worship,
        'arc_file': "s302.arc",
        'ap_id': 4861304},
    {'name': "4-2 Giant Majini Blue Enigma near Sea Emblem",
        'chapter': Chapters.c42_worship,
        'arc_file': "s302.arc",
        'ap_id': 4861305},
#    {'name': "",
#        'chapter': Chapters.c42_worship,
#        'arc_file': "s302.arc",
#        'ap_id': 4861306},
    {'name': "4-2 Green Herb near Sky Emblem 2",
        'chapter': Chapters.c42_worship,
        'arc_file': "s302.arc",
        'ap_id': 4861307},
    {'name': "4-2 Proximity Mine behind Sea Emblem Laser",
        'chapter': Chapters.c42_worship,
        'arc_file': "s302.arc",
        'ap_id': 4861308},
#    {'name': "",
#        'chapter': Chapters.c42_worship,
#        'arc_file': "s302.arc",
#        'ap_id': 4861309},
    {'name': "4-2 Ruby Pear between Twin Lasers",
        'chapter': Chapters.c42_worship,
        'arc_file': "s302.arc",
        'ap_id': 4861310},
    {'name': "4-2 Sapphire Pear on Stairs near Earth Emblem",
        'chapter': Chapters.c42_worship,
        'arc_file': "s302.arc",
        'ap_id': 4861311},
    {'name': "4-2 Emerald Pear near Right Side Laser",
        'chapter': Chapters.c42_worship,
        'arc_file': "s302.arc",
        'ap_id': 4861312},
    {'name': "4-2 Diamond Trilliant above Worship Area Exit",
        'chapter': Chapters.c42_worship,
        'arc_file': "s302.arc",
        'ap_id': 4861313},
    {'name': "4-2 Topaz Opal in Crevace near Sea Emblem",
        'chapter': Chapters.c42_worship,
        'arc_file': "s302.arc",
        'ap_id': 4861314},
    {'name': "4-2 Sapphire Square in Crevace near Earth Emblem",
        'chapter': Chapters.c42_worship,
        'arc_file': "s302.arc",
        'ap_id': 4861315},
    {'name': "4-2 Emerald Pear in Mask Mirror B3",
        'chapter': Chapters.c42_pyramid,
        'arc_file': "s303.arc",
        'ap_id': 4861316},
    {'name': "4-2 Ruby Pear Mirror B2 Safe Spot",
        'chapter': Chapters.c42_pyramid,
        'arc_file': "s303.arc",
        'ap_id': 4861317},
    {'name': "4-2 Idol Room Vases Mirror B3 1",
        'chapter': Chapters.c42_pyramid,
        'arc_file': "s303.arc",
        'ap_id': 4861318},
    {'name': "4-2 Idol Room Vases Mirror B3 2",
        'chapter': Chapters.c42_pyramid,
        'arc_file': "s303.arc",
        'ap_id': 4861319},
    {'name': "4-2 Idol Room Vases Mirror B3 3",
        'chapter': Chapters.c42_pyramid,
        'arc_file': "s303.arc",
        'ap_id': 4861320},
    {'name': "4-2 Idol Room Vases Mirror B3 4",
        'chapter': Chapters.c42_pyramid,
        'arc_file': "s303.arc",
        'ap_id': 4861321},
    {'name': "4-2 Idol Room Vases Mirror B3 5",
        'chapter': Chapters.c42_pyramid,
        'arc_file': "s303.arc",
        'ap_id': 4861322},
    {'name': "4-2 Idol Room Vases Mirror B3 6",
        'chapter': Chapters.c42_pyramid,
        'arc_file': "s303.arc",
        'ap_id': 4861323},
#    {'name': "",
#        'chapter': Chapters.c42_pyramid,
#        'arc_file': "s303.arc",
#        'ap_id': 4861324},
#    {'name': "",
#        'chapter': Chapters.c42_pyramid,
#        'arc_file': "s303.arc",
#        'ap_id': 4861325},
#    {'name': "",
#        'chapter': Chapters.c42_pyramid,
#        'arc_file': "s303.arc",
#        'ap_id': 4861326},
#    {'name': "",
#        'chapter': Chapters.c42_pyramid,
#        'arc_file': "s303.arc",
#        'ap_id': 4861327},
#    {'name': "",
#        'chapter': Chapters.c42_pyramid,
#        'arc_file': "s303.arc",
#        'ap_id': 4861328},
#    {'name': "",
#        'chapter': Chapters.c42_pyramid,
#        'arc_file': "s303.arc",
#        'ap_id': 4861329},
    {'name': "4-2 Gold Beetle Mirror B3",
        'chapter': Chapters.c42_pyramid,
        'arc_file': "s303.arc",
        'ap_id': 4861330},
    {'name': "4-2 Gold Idol Mirror B3",
        'chapter': Chapters.c42_pyramid,
        'arc_file': "s303.arc",
        'ap_id': 4861331},
    {'name': "4-2 Ruby Pear in Mask Mirror B3",
        'chapter': Chapters.c42_pyramid,
        'arc_file': "s303.arc",
        'ap_id': 4861332},
#    {'name': "",
#        'chapter': Chapters.c52_experiment,
#        'arc_file': "s304.arc",
#        'ap_id': 4861333},
    {'name': "5-1 Hand Grenade during Ultimate-8 Fight",
        'chapter': Chapters.c52_experiment,
        'arc_file': "s304.arc",
        'ap_id': 4861334},
    {'name': "5-1 Ammo Shelf before Ultimate-8 2",
        'chapter': Chapters.c52_experiment,
        'arc_file': "s304.arc",
        'ap_id': 4861335},
#    {'name': "",
#        'chapter': Chapters.c52_experiment,
#        'arc_file': "s304.arc",
#        'ap_id': 4861336},
#    {'name': "",
#        'chapter': Chapters.c52_experiment,
#        'arc_file': "s304.arc",
#        'ap_id': 4861337},
    {'name': "5-1 Green Herb during Ultimate-8 Fight",
        'chapter': Chapters.c52_experiment,
        'arc_file': "s304.arc",
        'ap_id': 4861338},
    {'name': "5-1 Ammo Shelf before Ultimate-8 5",
        'chapter': Chapters.c52_experiment,
        'arc_file': "s304.arc",
        'ap_id': 4861339},
    {'name': "5-1 Ammo Shelf before Ultimate-8 3",
        'chapter': Chapters.c52_experiment,
        'arc_file': "s304.arc",
        'ap_id': 4861340},
    {'name': "5-1 Ammo Shelf before Ultimate-8 4",
        'chapter': Chapters.c52_experiment,
        'arc_file': "s304.arc",
        'ap_id': 4861341},
    {'name': "5-1 Ammo Shelf before Ultimate-8 1",
        'chapter': Chapters.c52_experiment,
        'arc_file': "s304.arc",
        'ap_id': 4861342},
    {'name': "5-1 Shotgun Ammo in Plant Room",
        'chapter': Chapters.c51_progenitor,
        'arc_file': "s305.arc",
        'ap_id': 4861343},
    {'name': "5-1 Machinegun Ammo in Server Room",
        'chapter': Chapters.c51_progenitor,
        'arc_file': "s305.arc",
        'ap_id': 4861344},
    {'name': "5-1 Green Herb near Dog Cages",
        'chapter': Chapters.c51_progenitor,
        'arc_file': "s305.arc",
        'ap_id': 4861345},
    {'name': "5-1 Green Herb in Server Hallway",
        'chapter': Chapters.c51_progenitor,
        'arc_file': "s305.arc",
        'ap_id': 4861346},
    {'name': "5-1 Incendiary Grenade in Server Room",
        'chapter': Chapters.c51_progenitor,
        'arc_file': "s305.arc",
        'ap_id': 4861347},
    {'name': "5-1 Handgun Ammo before Licker Hallway",
        'chapter': Chapters.c51_progenitor,
        'arc_file': "s305.arc",
        'ap_id': 4861348},
    {'name': "5-1 Red Herb near AK-74 Briefcase",
        'chapter': Chapters.c51_progenitor,
        'arc_file': "s305.arc",
        'ap_id': 4861349},
    {'name': "5-1 Safe near AK-74 Briefcase",
        'chapter': Chapters.c51_progenitor,
        'arc_file': "s305.arc",
        'ap_id': 4861350},
    {'name': "5-1 Handgun Ammo in Server Room",
        'chapter': Chapters.c51_progenitor,
        'arc_file': "s305.arc",
        'ap_id': 4861351},
#    {'name': "",
#        'chapter': Chapters.c51_progenitor,
#        'arc_file': "s305.arc",
#        'ap_id': 4861352},
#    {'name': "",
#        'chapter': Chapters.c51_progenitor,
#        'arc_file': "s305.arc",
#        'ap_id': 4861353},
#    {'name': "",
#        'chapter': Chapters.c51_progenitor,
#        'arc_file': "s305.arc",
#        'ap_id': 4861354},
    {'name': "5-1 Licker Lion Heart 1", # Missable as it's an RNG drop
        'chapter': Chapters.c51_progenitor,
       'arc_file': "s305.arc",
        'ap_id': 4861355},
    {'name': "5-1 Licker Lion Heart 4",
        'chapter': Chapters.c51_progenitor,
        'arc_file': "s305.arc",
        'ap_id': 4861356},
    {'name': "5-1 AK-74 Briefcase",
        'chapter': Chapters.c51_progenitor,
        'arc_file': "s305.arc",
        'ap_id': 4861357},
    {'name': "5-1 Licker Lion Heart 2", # Missable as it's an RNG drop
        'chapter': Chapters.c51_progenitor,
        'arc_file': "s305.arc",
        'ap_id': 4861358},
    {'name': "5-1 Licker Lion Heart 3", # Missable as it's an RNG drop
        'chapter': Chapters.c51_progenitor,
        'arc_file': "s305.arc",
        'ap_id': 4861359},
    {'name': "5-2 Green Herb near Explosives Conveyor",
        'chapter': Chapters.c52_missile1,
        'arc_file': "s307.arc",
        'ap_id': 4861360},
    {'name': "5-2 Handgun Ammo near Steel Box Conveyor",
        'chapter': Chapters.c52_missile1,
        'arc_file': "s307.arc",
        'ap_id': 4861361},
    {'name': "5-2 Handgun Ammo near Explosives Conveyor",
        'chapter': Chapters.c52_missile1,
        'arc_file': "s307.arc",
        'ap_id': 4861362},
#    {'name': "",
#        'chapter': Chapters.c52_missile1,
#        'arc_file': "s307.arc",
#        'ap_id': 4861363},
    {'name': "5-2 SIG 556 Briefcase",
        'chapter': Chapters.c52_missile1,
        'arc_file': "s307.arc",
        'ap_id': 4861364},
    {'name': "5-2 Machinegun Ammo near Missile Area Reaper Eggs",
        'chapter': Chapters.c52_missile1,
        'arc_file': "s307.arc",
        'ap_id': 4861365},
#    {'name': "",
#        'chapter': Chapters.c52_missile1,
#        'arc_file': "s307.arc",
#        'ap_id': 4861366},
    {'name': "5-2 Red Herb near Steel Box Conveyor",
        'chapter': Chapters.c52_missile1,
        'arc_file': "s307.arc",
        'ap_id': 4861367},
    {'name': "5-2 Reaper Power Stone 1",
        'chapter': Chapters.c52_missile1,
        'arc_file': "s307.arc",
        'ap_id': 4861368},
    {'name': "5-2 Dead Bride's Necklace from Conveyor Zombie 1",
        'chapter': Chapters.c52_missile1,
        'arc_file': "s307.arc",
        'ap_id': 4861369},
    {'name': "5-2 Dead Bride's Necklace from Conveyor Zombie 2",
        'chapter': Chapters.c52_missile1,
        'arc_file': "s307.arc",
        'ap_id': 4861370},
#    {'name': "",
#        'chapter': Chapters.c52_missile1,
#        'arc_file': "s307.arc",
#        'ap_id': 4861371},
    {'name': "5-2 Red Herb near Missile Area Generator",
        'chapter': Chapters.c52_missile1,
        'arc_file': "s307.arc",
        'ap_id': 4861372},
    {'name': "5-2 Grenade beside SIG 556",
        'chapter': Chapters.c52_missile1,
        'arc_file': "s307.arc",
        'ap_id': 4861373},
#    {'name': "",
#        'chapter': Chapters.c52_missile1,
#        'arc_file': "s307.arc",
#        'ap_id': 4861374},
#    {'name': "",
#        'chapter': Chapters.c52_mkono,
#        'arc_file': "s308.arc",
#        'ap_id': 4861375},
#    {'name': "",
#        'chapter': Chapters.c52_mkono,
#        'arc_file': "s308.arc",
#        'ap_id': 4861376},
    {'name': "5-2 Green Herb in Mkono Fight",
        'chapter': Chapters.c52_mkono,
        'arc_file': "s308.arc",
        'ap_id': 4861377},
#    {'name': "",
#        'chapter': Chapters.c52_mkono,
#        'arc_file': "s308.arc",
#        'ap_id': 4861378},
    {'name': "5-3 Machinegun Ammo in Mkono Office Hallway",
        'chapter': Chapters.c53_uroboros,
        'arc_file': "s308.arc",
        'ap_id': 4861379},
    {'name': "5-3 Ammo on Mkono Office Desk 1",
        'chapter': Chapters.c53_uroboros,
        'arc_file': "s308.arc",
        'ap_id': 4861380},
    {'name': "5-3 Ammo on Mkono Office Desk 2",
        'chapter': Chapters.c53_uroboros,
        'arc_file': "s308.arc",
        'ap_id': 4861381},
    {'name': "5-2 Ammo near Throne in Mkono Fight 2",
        'chapter': Chapters.c52_mkono,
        'arc_file': "s308.arc",
        'ap_id': 4861382},
    {'name': "5-2 Ammo near Flamethrower in Mkono Fight 1",
        'chapter': Chapters.c52_mkono,
        'arc_file': "s308.arc",
        'ap_id': 4861383},
    {'name': "5-2 Ammo near Flamethrower in Mkono Fight 2",
        'chapter': Chapters.c52_mkono,
        'arc_file': "s308.arc",
        'ap_id': 4861384},
    {'name': "5-2 Handgun Ammo before Uroboros Mkono 2",
        'chapter': Chapters.c52_mkono,
        'arc_file': "s308.arc",
        'ap_id': 4861385},
    {'name': "5-2 Grenade near Front Terminal in Mkono Fight",
        'chapter': Chapters.c52_mkono,
        'arc_file': "s308.arc",
        'ap_id': 4861386},
    {'name': "5-2 First Aid in Mkono Fight",
        'chapter': Chapters.c52_mkono,
        'arc_file': "s308.arc",
        'ap_id': 4861387},
    {'name': "5-2 Handgun Ammo before Uroboros Mkono 1",
        'chapter': Chapters.c52_mkono,
        'arc_file': "s308.arc",
        'ap_id': 4861388},
    {'name': "5-2 Ammo near Throne in Mkono Fight 1",
        'chapter': Chapters.c52_mkono,
        'arc_file': "s308.arc",
        'ap_id': 4861389},
    {'name': "5-2 Incendiary Grenade before Uroboros Mkono",
        'chapter': Chapters.c52_mkono,
        'arc_file': "s308.arc",
        'ap_id': 4861390},
#    {'name': "",
#        'chapter': Chapters.c52_mkono,
#        'arc_file': "s308.arc",
#        'ap_id': 4861391},
    {'name': "5-2 First Aid next to Throne in Mkono Fight",
        'chapter': Chapters.c52_mkono,
        'arc_file': "s308.arc",
        'ap_id': 4861392},
    {'name': "5-2 Ammo near Throne in Mkono Fight 3",
        'chapter': Chapters.c52_mkono,
        'arc_file': "s308.arc",
        'ap_id': 4861393},
    {'name': "5-2 Ammo near Front Terminal in Mkono Fight",
        'chapter': Chapters.c52_mkono,
        'arc_file': "s308.arc",
        'ap_id': 4861394},
    {'name': "5-2 Flame Rounds before Uroboros Mkono",
        'chapter': Chapters.c52_mkono,
        'arc_file': "s308.arc",
        'ap_id': 4861395},
    {'name': "5-2 Rifle Rounds before Uroboros Mkono",
        'chapter': Chapters.c52_mkono,
        'arc_file': "s308.arc",
        'ap_id': 4861396},
 #   {'name': "",
#        'chapter': Chapters.c52_mkono,
#        'arc_file': "s308.arc",
#        'ap_id': 4861397},
    {'name': "5-2 Incendiary near Throne in Mkono Fight 1",
        'chapter': Chapters.c52_mkono,
        'arc_file': "s308.arc",
        'ap_id': 4861398},
    {'name': "5-2 Incendiary near Throne in Mkono Fight 2",
        'chapter': Chapters.c52_mkono,
        'arc_file': "s308.arc",
        'ap_id': 4861399},
    {'name': "5-3 Sapphire Marquise in Safe",
        'chapter': Chapters.c53_uroboros,
        'arc_file': "s308.arc",
        'ap_id': 4861400},
    {'name': "5-3 L. Hawk Sarcophagus 1",
        'chapter': Chapters.c53_jill,
        'arc_file': "s309.arc",
        'ap_id': 4861401},
#    {'name': "",
#        'chapter': Chapters.c53_jill,
#        'arc_file': "s309.arc",
#        'ap_id': 4861402},
    {'name': "5-3 Emerald Pear Far Right Walkway 2F during Wesker",
        'chapter': Chapters.c53_jill,
        'arc_file': "s309.arc",
        'ap_id': 4861403},
    {'name': "5-3 L. Hawk Sarcophagus 2",
        'chapter': Chapters.c53_jill,
        'arc_file': "s309.arc",
        'ap_id': 4861404},
    {'name': "5-3 L. Hawk Sarcophagus 3",
        'chapter': Chapters.c53_jill,
        'arc_file': "s309.arc",
        'ap_id': 4861405},
    {'name': "5-3 Flash Grenade Far Right Walkway 2F during Wesker",
        'chapter': Chapters.c53_jill,
        'arc_file': "s309.arc",
        'ap_id': 4861406},
    {'name': "5-3 Something A",
        'chapter': Chapters.c53_jill,
        'arc_file': "s309.arc",
        'ap_id': 4861407},
    {'name': "5-3 Something B",
        'chapter': Chapters.c53_jill,
        'arc_file': "s309.arc",
        'ap_id': 4861408},
    {'name': "5-3 Green Herb under Stairs during Wesker 1",
        'chapter': Chapters.c53_jill,
        'arc_file': "s309.arc",
        'ap_id': 4861409},
    {'name': "5-3 Green Herb under Stairs during Wesker 2",
        'chapter': Chapters.c53_jill,
        'arc_file': "s309.arc",
        'ap_id': 4861410},
#    {'name': "",
#        'chapter': Chapters.c53_jill,
#        'arc_file': "s309.arc",
#        'ap_id': 4861411},
#    {'name': "",
#        'chapter': Chapters.c52_power,
#        'arc_file': "s310.arc",
#        'ap_id': 4861412},
#    {'name': "",
#        'chapter': Chapters.c52_power,
#        'arc_file': "s310.arc",
#        'ap_id': 4861413},
    {'name': "5-2 Green Herb at Power Entrance",
        'chapter': Chapters.c52_power,
        'arc_file': "s310.arc",
        'ap_id': 4861414},
    {'name': "5-2 Red Herb at Broken Stairs",
        'chapter': Chapters.c52_power,
        'arc_file': "s310.arc",
        'ap_id': 4861415},
    {'name': "5-3 Rifle Ammo behind Bridge Elevator",
        'chapter': Chapters.c53_monarch,
        'arc_file': "s311.arc",
        'ap_id': 4861416},
    {'name': "5-3 Rifle Ammo on Bridge Control Roof",
        'chapter': Chapters.c53_monarch,
        'arc_file': "s311.arc",
        'ap_id': 4861417},
    {'name': "5-3 Green Herb in Bridge Control Room",
        'chapter': Chapters.c53_monarch,
        'arc_file': "s311.arc",
        'ap_id': 4861418},
    {'name': "5-3 First Aid in Bridge Control Room",
        'chapter': Chapters.c53_monarch,
        'arc_file': "s311.arc",
        'ap_id': 4861419},
    {'name': "5-3 Gold Chalice in Bridge Control Room",
        'chapter': Chapters.c53_monarch,
        'arc_file': "s311.arc",
        'ap_id': 4861420},
#    {'name': "",
#        'chapter': Chapters.c53_monarch,
#        'arc_file': "s311.arc",
#        'ap_id': 4861421},
    {'name': "5-3 Ruby Marquise above Drawbridge",
        'chapter': Chapters.c53_monarch,
        'arc_file': "s311.arc",
        'ap_id': 4861422},
    {'name': "5-3 Licker Lion Heart 1",
        'chapter': Chapters.c53_monarch,
        'arc_file': "s311.arc",
        'ap_id': 4861423},
#    {'name': "",
#        'chapter': Chapters.c53_monarch,
#        'arc_file': "s311.arc",
#        'ap_id': 4861424},
#    {'name': "",
#        'chapter': Chapters.c53_monarch,
#        'arc_file': "s311.arc",
#        'ap_id': 4861425},
    {'name': "5-3 Licker Lion Heart 2",
        'chapter': Chapters.c53_monarch,
        'arc_file': "s311.arc",
        'ap_id': 4861426},
#    {'name': "",
#        'chapter': Chapters.c53_monarch,
#        'arc_file': "s311.arc",
#        'ap_id': 4861427},
    {'name': "5-1 Emerald Pear on Garden Ceiling",
        'chapter': Chapters.c51_garden,
        'arc_file': "s312.arc",
        'ap_id': 4861428},
    {'name': "5-1 Ruby Square above Garden Entrance",
        'chapter': Chapters.c51_garden,
        'arc_file': "s312.arc",
        'ap_id': 4861429},
#    {'name': "",   ### Probably the lore in the Garden
#        'chapter': Chapters.c51_garden,
#        'arc_file': "s312.arc",
#        'ap_id': 4861430},
#    {'name': "",   ### Probably the lore near the exit
#        'chapter': Chapters.c51_garden,
#        'arc_file': "s312.arc",
#        'ap_id': 4861431},
    {'name': "5-1 Jewel Beetle in Garden",
        'chapter': Chapters.c51_garden,
        'arc_file': "s312.arc",
        'ap_id': 4861432},
    {'name': "4-1 Brilliant Topaz in Chest",
        'chapter': Chapters.c41_caves,
        'arc_file': "s313.arc",
        'ap_id': 4861433},
    {'name': "4-1 Flash Grenade in Vase near Boat",
        'chapter': Chapters.c41_caves,
        'arc_file': "s313.arc",
        'ap_id': 4861434},
    {'name': "4-1 Emerald Pear in Standing Lantern",
        'chapter': Chapters.c41_caves,
        'arc_file': "s313.arc",
        'ap_id': 4861435},
    {'name': "4-1 Topaz Pear in Torch before Door",
        'chapter': Chapters.c41_caves,
        'arc_file': "s313.arc",
        'ap_id': 4861436},
    {'name': "4-1 Sapphire Square in Ground Lantern",
        'chapter': Chapters.c41_caves,
        'arc_file': "s313.arc",
        'ap_id': 4861437},
    {'name': "4-1 Ruby Pear in Mask before Door",
        'chapter': Chapters.c41_caves,
        'arc_file': "s313.arc",
        'ap_id': 4861438},
    {'name': "4-1 Sapphire Pear in Mask before Door",
        'chapter': Chapters.c41_caves,
        'arc_file': "s313.arc",
        'ap_id': 4861439},
    {'name': "4-1 Square Topaz on Roof behind Chest",
        'chapter': Chapters.c41_caves,
        'arc_file': "s313.arc",
        'ap_id': 4861440},
    {'name': "5-3 Handgun Ammo near H&K PSG-1 Briefcase",
        'chapter': Chapters.c53_missile2,
        'arc_file': "s314.arc",
        'ap_id': 4861441},
    {'name': "5-3 H&K PSG-1 Briefcase",
        'chapter': Chapters.c53_missile2,
        'arc_file': "s314.arc",
        'ap_id': 4861442},
#    {'name': "",
#        'chapter': Chapters.c53_missile2,
#        'arc_file': "s314.arc",
#        'ap_id': 4861443},
    {'name': "5-3 Red Herb near H&K PSG-1 Briefcase",
        'chapter': Chapters.c53_missile2,
        'arc_file': "s314.arc",
        'ap_id': 4861444},
#    {'name': "",
#        'chapter': Chapters.c53_missile2,
#        'arc_file': "s314.arc",
#        'ap_id': 4861445},
    {'name': "5-3 Green Herb in Rocket Majini Room",
        'chapter': Chapters.c53_missile2,
        'arc_file': "s314.arc",
        'ap_id': 4861446},
    {'name': "5-2 Reaper Power Stone 2", # Missable RNG Drop
        'chapter': Chapters.c53_missile2,
        'arc_file': "s314.arc",
        'ap_id': 4861447},
#    {'name': "",
#        'chapter': Chapters.c53_missile2,
#        'arc_file': "s314.arc",
#        'ap_id': 4861448},
    {'name': "5-3 Royal Necklace in Rocket Majini Room",
        'chapter': Chapters.c53_missile2,
        'arc_file': "s314.arc",
        'ap_id': 4861449},
    {'name': "5-3 Fat Man Jewel Bangle", # Fat Man Majini on the moving platform
        'chapter': Chapters.c53_missile2,
        'arc_file': "s314.arc",
        'ap_id': 4861450},
    {'name': "5-2 Reaper Power Stone A?", # Missable RNG Drop
        'chapter': Chapters.c53_missile2,
        'arc_file': "s314.arc",
        'ap_id': 4861451},
#    {'name': "",
#        'chapter': Chapters.c53_missile2,
#        'arc_file': "s314.arc",
#        'ap_id': 4861452},
#    {'name': "",
#        'chapter': Chapters.c53_missile2,
#        'arc_file': "s314.arc",
#        'ap_id': 4861453},
#    {'name': "",
#        'chapter': Chapters.c53_missile2,
#        'arc_file': "s314.arc",
#        'ap_id': 4861454},
#    {'name': "",
#        'chapter': Chapters.c53_missile2,
#        'arc_file': "s314.arc",
#        'ap_id': 4861455},
    {'name': "5-3 Electric Rounds near Missile Area 2",
        'chapter': Chapters.c53_missile2,
        'arc_file': "s314.arc",
        'ap_id': 4861456},
    {'name': "5-3 Rifle Ammo before Massive Elevator 1",
        'chapter': Chapters.c53_platform,
        'arc_file': "s315.arc",
        'ap_id': 4861457},
    {'name': "5-3 Rifle Ammo before Massive Elevator 2",
        'chapter': Chapters.c53_platform,
        'arc_file': "s315.arc",
        'ap_id': 4861458},
    {'name': "5-3 Green Herb near Massive Elevator",
        'chapter': Chapters.c53_platform,
        'arc_file': "s315.arc",
        'ap_id': 4861459},
    {'name': "5-2 Green Herb before Licker Hallway",
        'chapter': Chapters.c52_facpassage,
        'arc_file': "s316.arc",
        'ap_id': 4861460},
    {'name': "5-2 Licker Lion Heart 2",
        'chapter': Chapters.c52_facpassage,
        'arc_file': "s316.arc",
        'ap_id': 4861461},
    {'name': "5-2 Licker Lion Heart 5",
        'chapter': Chapters.c52_facpassage,
        'arc_file': "s316.arc",
        'ap_id': 4861462},
    {'name': "5-2 Licker Lion Heart 4",
        'chapter': Chapters.c52_facpassage,
        'arc_file': "s316.arc",
        'ap_id': 4861463},
    {'name': "5-2 Licker Lion Heart 1",
        'chapter': Chapters.c52_facpassage,
        'arc_file': "s316.arc",
        'ap_id': 4861464},
    {'name': "5-2 Licker Lion Heart 3",
        'chapter': Chapters.c52_facpassage,
        'arc_file': "s316.arc",
        'ap_id': 4861465},
#    {'name': "",
#        'chapter': Chapters.c61_deck,
#        'arc_file': "s500.arc",
#        'ap_id': 4861466},
    {'name': "6-1 Green Herb at Back of Ship",
        'chapter': Chapters.c61_deck,
        'arc_file': "s500.arc",
        'ap_id': 4861467},
    {'name': "6-1 Rifle Ammo on Emblem Longshot Tower",
        'chapter': Chapters.c61_deck,
        'arc_file': "s500.arc",
        'ap_id': 4861468},
    {'name': "6-1 Green Herb after Crate Trap",
        'chapter': Chapters.c61_deck,
        'arc_file': "s500.arc",
        'ap_id': 4861469},
    {'name': "6-1 Gold Bar Safe Guarded by Dog",
        'chapter': Chapters.c61_deck,
        'arc_file': "s500.arc",
        'ap_id': 4861470},
    {'name': "6-1 Gold Bar Safe after Crate Trap",
        'chapter': Chapters.c61_deck,
        'arc_file': "s500.arc",
        'ap_id': 4861471},
    {'name': "6-1 Fat Man Jewel Bangle 2",
        'chapter': Chapters.c61_deck,
        'arc_file': "s500.arc",
        'ap_id': 4861472},
    {'name': "6-1 Fat Man Jewel Bangle 3",
        'chapter': Chapters.c61_deck,
        'arc_file': "s500.arc",
        'ap_id': 4861473},
    {'name': "6-1 Red Herb after Dog Ambush",
        'chapter': Chapters.c61_deck,
        'arc_file': "s500.arc",
        'ap_id': 4861474},
    {'name': "6-1 Crane Keycard",
        'chapter': Chapters.c61_deck,
        'arc_file': "s500.arc",
        'ap_id': 4861475},
    {'name': "6-1 Fat Man Jewel Bangle 1",
        'chapter': Chapters.c61_deck,
        'arc_file': "s500.arc",
        'ap_id': 4861476},
#    {'name': "",
#        'chapter': Chapters.c61_deck,
#        'arc_file': "s500.arc",
#        'ap_id': 4861477},
#    {'name': "",
#        'chapter': Chapters.c61_deck,
#        'arc_file': "s500.arc",
#        'ap_id': 4861478},
#    {'name': "",
#        'chapter': Chapters.c61_deck,
#        'arc_file': "s500.arc",
#        'ap_id': 4861479},
#    {'name': "",
#        'chapter': Chapters.c61_deck,
#        'arc_file': "s500.arc",
#        'ap_id': 4861480},
    {'name': "6-1 Flash Grenade after Dog Ambush",
        'chapter': Chapters.c61_deck,
        'arc_file': "s500.arc",
        'ap_id': 4861481},
#    {'name': "",
#        'chapter': Chapters.c61_deck,
#        'arc_file': "s500.arc",
#        'ap_id': 4861482},
#    {'name': "",
#        'chapter': Chapters.c61_deck,
#        'arc_file': "s500.arc",
#        'ap_id': 4861483},
#    {'name': "",
#        'chapter': Chapters.c61_deck,
#        'arc_file': "s500.arc",
#        'ap_id': 4861484},
#    {'name': "",
#        'chapter': Chapters.c61_deck,
#        'arc_file': "s500.arc",
#        'ap_id': 4861485},
    {'name': "6-1 Tanker Keycard A",
        'chapter': Chapters.c61_hold,
        'arc_file': "s501.arc",
        'ap_id': 4861486},
    {'name': "6-1 Tanker Keycard B",
        'chapter': Chapters.c61_hold,
        'arc_file': "s501.arc",
        'ap_id': 4861487},
    {'name': "6-1 Green Herb in Excella's Lab",
        'chapter': Chapters.c61_hold,
        'arc_file': "s501.arc",
        'ap_id': 4861488},
    {'name': "6-1 Green Herb in Cargo Hold",
        'chapter': Chapters.c61_hold,
        'arc_file': "s501.arc",
        'ap_id': 4861489},
#    {'name': "",
#        'chapter': Chapters.c61_hold,
#        'arc_file': "s501.arc",
#        'ap_id': 4861490},
    {'name': "6-1 Machinegun Ammo in Cargo Hold",
        'chapter': Chapters.c61_hold,
        'arc_file': "s501.arc",
        'ap_id': 4861491},
#    {'name': "",
#        'chapter': Chapters.c61_hold,
#        'arc_file': "s501.arc",
#        'ap_id': 4861492},
    {'name': "6-1 Rifle Ammo in Excella's Lab",
        'chapter': Chapters.c61_hold,
        'arc_file': "s501.arc",
        'ap_id': 4861493},
#    {'name': "",
#        'chapter': Chapters.c61_hold,
#        'arc_file': "s501.arc",
#        'ap_id': 4861494},
    {'name': "6-1 Ship Hold Entry Shelf 1",
        'chapter': Chapters.c61_hold,
        'arc_file': "s501.arc",
        'ap_id': 4861495},
    {'name': "6-1 Ship Hold Entry Shelf 2",
        'chapter': Chapters.c61_hold,
        'arc_file': "s501.arc",
        'ap_id': 4861496},
    {'name': "6-1 Ship Hold Entry Shelf 3",
        'chapter': Chapters.c61_hold,
        'arc_file': "s501.arc",
        'ap_id': 4861497},
#    {'name': "",
#        'chapter': Chapters.c61_hold,
#        'arc_file': "s501.arc",
#        'ap_id': 4861498},
    {'name': "6-1 Jail Breaker Briefcase",
        'chapter': Chapters.c61_hold,
        'arc_file': "s501.arc",
        'ap_id': 4861499},
#    {'name': "",
#        'chapter': Chapters.c61_hold,
#        'arc_file': "s501.arc",
#        'ap_id': 4861500},
    {'name': "6-1 Red Herb in Back of Cargo Hold",
        'chapter': Chapters.c61_hold,
        'arc_file': "s501.arc",
        'ap_id': 4861501},
    {'name': "6-1 Shotgun Ammo on Box in Back of Cargo Hold 2",
        'chapter': Chapters.c61_hold,
        'arc_file': "s501.arc",
        'ap_id': 4861502},
    {'name': "6-1 Dead Bride's Necklack in Rocket Launcher Room 1",
        'chapter': Chapters.c61_hold,
        'arc_file': "s501.arc",
        'ap_id': 4861503},
    {'name': "6-1 Dead Bride's Necklack in Rocket Launcher Room 2",
        'chapter': Chapters.c61_hold,
        'arc_file': "s501.arc",
        'ap_id': 4861504},
    {'name': "6-1 Dead Bride's Necklack in Rocket Launcher Room 3",
        'chapter': Chapters.c61_hold,
        'arc_file': "s501.arc",
        'ap_id': 4861505},
#    {'name': "",
#        'chapter': Chapters.c61_hold,
#        'arc_file': "s501.arc",
#        'ap_id': 4861506},
    {'name': "6-1 Grenade on Box in Back of Cargo Hold 1",
        'chapter': Chapters.c61_hold,
        'arc_file': "s501.arc",
        'ap_id': 4861507},
    {'name': "6-1 Grenade on Box in Back of Cargo Hold 2",
        'chapter': Chapters.c61_hold,
        'arc_file': "s501.arc",
        'ap_id': 4861508},
#    {'name': "",
#        'arc_file': "s501.arc",
#        'ap_id': 4861509},
#    {'name': "",
#        'chapter': Chapters.c62_deck,
#        'arc_file': "s503.arc",
#        'ap_id': 4861510},
#    {'name': "",
#        'chapter': Chapters.c62_deck,
#        'arc_file': "s503.arc",
#        'ap_id': 4861511},
    {'name': "6-2 Bridge Keycard",
        'chapter': Chapters.c62_bridge,
        'arc_file': "s504.arc",
        'ap_id': 4861512},
    {'name': "6-2 Green Herb after Uroboros Aheri",
        'chapter': Chapters.c62_bridge,
        'arc_file': "s504.arc",
        'ap_id': 4861513},
    {'name': "6-2 Shotgun Ammo near Bunk Room Corpse",
        'chapter': Chapters.c62_bridge,
        'arc_file': "s504.arc",
        'ap_id': 4861514},
#    {'name': "",
#        'chapter': Chapters.c62_bridge,
#        'arc_file': "s504.arc",
#        'ap_id': 4861515},
#    {'name': "",
#        'chapter': Chapters.c62_bridge,
#        'arc_file': "s504.arc",
#        'ap_id': 4861516},
    {'name': "6-2 Green Herb in Upstairs Meeting Room",
        'chapter': Chapters.c62_bridge,
        'arc_file': "s504.arc",
        'ap_id': 4861517},
    {'name': "6-2 Rifle Ammo in Bunk Room Locker",
        'chapter': Chapters.c62_bridge,
        'arc_file': "s504.arc",
        'ap_id': 4861518},
#    {'name': "",
#        'chapter': Chapters.c62_bridge,
#        'arc_file': "s504.arc",
#        'ap_id': 4861519},
#    {'name': "",
#        'chapter': Chapters.c62_bridge,
#        'arc_file': "s504.arc",
#        'ap_id': 4861520},
    {'name': "6-2 Handgun Ammo in Entryway Locker 1",
        'chapter': Chapters.c62_bridge,
        'arc_file': "s504.arc",
        'ap_id': 4861521},
#    {'name': "",
#        'chapter': Chapters.c62_bridge,
#        'arc_file': "s504.arc",
#        'ap_id': 4861522},
#    {'name': "",
#        'chapter': Chapters.c62_bridge,
#        'arc_file': "s504.arc",
#        'ap_id': 4861523},
#    {'name': "",
#        'chapter': Chapters.c62_bridge,
#        'arc_file': "s504.arc",
#        'ap_id': 4861524},
    {'name': "6-2 Proximity Mine on Bunk Room Corpse",
        'chapter': Chapters.c62_bridge,
        'arc_file': "s504.arc",
        'ap_id': 4861525},
    {'name': "6-2 Gold Chalice in Entryway Locker 2",
        'chapter': Chapters.c62_bridge,
        'arc_file': "s504.arc",
        'ap_id': 4861526},
    {'name': "6-2 Gold Chalice in Upstairs Meeting Room Locker",
        'chapter': Chapters.c62_bridge,
        'arc_file': "s504.arc",
        'ap_id': 4861527},
#    {'name': "",
#        'chapter': Chapters.c62_bridge,
#        'arc_file': "s504.arc",
#        'ap_id': 4861528},
    {'name': "6-3 Bulkhead Keycard A",
        'chapter': Chapters.c63_engine,
        'arc_file': "s505.arc",
        'ap_id': 4861529},
    {'name': "6-3 Bulkhead Keycard B",
        'chapter': Chapters.c63_engine,
        'arc_file': "s505.arc",
        'ap_id': 4861530},
#    {'name': "",
#        'chapter': Chapters.c63_engine,
#        'arc_file': "s505.arc",
#        'ap_id': 4861531},
    {'name': "6-3 Left Rafter's Storage Room 2",
        'chapter': Chapters.c63_engine,
        'arc_file': "s505.arc",
        'ap_id': 4861532},
    {'name': "6-3 Green Herb near Primary Bulkhead Reapers",
        'chapter': Chapters.c63_engine,
        'arc_file': "s505.arc",
        'ap_id': 4861533},
#    {'name': "",
#        'chapter': Chapters.c63_engine,
#        'arc_file': "s505.arc",
#        'ap_id': 4861534},
    {'name': "6-3 Green Herb beneath Primary Bulkhead Walkway",
        'chapter': Chapters.c63_engine,
        'arc_file': "s505.arc",
        'ap_id': 4861535},
    {'name': "6-3 Green Herb Left-Side Primary Bulkhead",
        'chapter': Chapters.c63_engine,
        'arc_file': "s505.arc",
        'ap_id': 4861536},
#    {'name': "",
#        'chapter': Chapters.c63_engine,
#        'arc_file': "s505.arc",
#        'ap_id': 4861537},
#    {'name': "",
#        'chapter': Chapters.c63_engine,
#        'arc_file': "s505.arc",
#        'ap_id': 4861538},
    {'name': "6-3 Green Herb behind Secondary Bulkhead Switch",
        'chapter': Chapters.c63_engine,
        'arc_file': "s505.arc",
        'ap_id': 4861539},
    {'name': "6-3 Reaper Power Stone 1",
        'chapter': Chapters.c63_engine,
        'arc_file': "s505.arc",
        'ap_id': 4861540},
    {'name': "6-3 Dead Bride's Necklace near Primary Bulkhead",
        'chapter': Chapters.c63_engine,
        'arc_file': "s505.arc",
        'ap_id': 4861541},
    {'name': "6-3 Dead Bride's Necklace in Upper Rafters",
        'chapter': Chapters.c63_engine,
        'arc_file': "s505.arc",
        'ap_id': 4861542},
#    {'name': "",
#        'chapter': Chapters.c63_engine,
#        'arc_file': "s505.arc",
#        'ap_id': 4861543},
#    {'name': "",
#        'chapter': Chapters.c63_engine,
#        'arc_file': "s505.arc",
#        'ap_id': 4861544},
#    {'name': "",
#        'chapter': Chapters.c63_engine,
#        'arc_file': "s505.arc",
#        'ap_id': 4861545},
    {'name': "6-3 Right Rafter's Storage Room 1",
        'chapter': Chapters.c63_engine,
        'arc_file': "s505.arc",
        'ap_id': 4861546},
    {'name': "6-3 Right Rafter's Storage Room 2",
        'chapter': Chapters.c63_engine,
        'arc_file': "s505.arc",
        'ap_id': 4861547},
    {'name': "6-3 Left Rafter's Storage Room 1",
        'chapter': Chapters.c63_engine,
        'arc_file': "s505.arc",
        'ap_id': 4861548},
#    {'name': "", # Apparently there are Acid rounds here? I only ever found Nitrogen in my 3 times running through. Someone help a guy out here.
#        'chapter': Chapters.c63_engine,
#        'arc_file': "s505.arc",
#        'ap_id': 4861549},
    {'name': "6-3 Left Rafter's Storage Room 3",
        'chapter': Chapters.c63_engine,
        'arc_file': "s505.arc",
        'ap_id': 4861550},
    {'name': "6-3 Magnum Ammo on Right-Side Rafters",
        'chapter': Chapters.c63_engine,
        'arc_file': "s505.arc",
        'ap_id': 4861551},
    {'name': "6-3 Handgun Ammo on Right-Side Rafters",
        'chapter': Chapters.c63_engine,
        'arc_file': "s505.arc",
        'ap_id': 4861552},
    {'name': "6-3 Hand Grenade between Bulkheads",
        'chapter': Chapters.c63_engine,
        'arc_file': "s505.arc",
        'ap_id': 4861553},
    {'name': "6-3 Hand Grenade in Flooded Bulkhead Entryway",
        'chapter': Chapters.c63_engine,
        'arc_file': "s505.arc",
        'ap_id': 4861554},
    {'name': "6-3 Flash Grenade after Primary Bulkhead 1",
        'chapter': Chapters.c63_engine,
        'arc_file': "s505.arc",
        'ap_id': 4861555},
    {'name': "6-3 Flash Grenade after Primary Bulkhead 2",
        'chapter': Chapters.c63_engine,
        'arc_file': "s505.arc",
        'ap_id': 4861556},
    {'name': "6-3 Flash Grenade after Primary Bulkhead 3",
        'chapter': Chapters.c63_engine,
        'arc_file': "s505.arc",
        'ap_id': 4861557},
    {'name': "6-3 Reaper Power Stone 2", # Missable, Requires killing all 3 reapers
        'chapter': Chapters.c63_engine,
        'arc_file': "s505.arc",
        'ap_id': 4861558},
    {'name': "6-3 Reaper Power Stone 3", # Missable, Requires killing all 3 reapers
        'chapter': Chapters.c63_engine,
        'arc_file': "s505.arc",
        'ap_id': 4861559},
    {'name': "6-3 RPG-7 NVG",
        'chapter': Chapters.c63_hangar,
        'arc_file': "s506.arc",
        'ap_id': 4861560},
    {'name': "6-3 Hangar RPG Shot 1", # 5 shots in Glass above the spawn
        'chapter': Chapters.c63_hangar,
        'arc_file': "s506.arc",
        'ap_id': 4861561},
    {'name': "6-3 Hangar RPG Shot 2", # 5 shots in Glass above the spawn
        'chapter': Chapters.c63_hangar,
        'arc_file': "s506.arc",
        'ap_id': 4861562},
    {'name': "6-3 Hangar RPG Shot 3", # 5 shots in Glass above the spawn
        'chapter': Chapters.c63_hangar,
        'arc_file': "s506.arc",
        'ap_id': 4861563},
    {'name': "6-3 Hangar RPG Shot 4", # 5 shots in Glass above the spawn
        'chapter': Chapters.c63_hangar,
        'arc_file': "s506.arc",
        'ap_id': 4861564},
    {'name': "6-3 Hangar RPG Shot 5", # 5 shots in Glass above the spawn
        'chapter': Chapters.c63_hangar,
        'arc_file': "s506.arc",
        'ap_id': 4861565},
    {'name': "6-3 Hangar RPG Shot 6", # Downstairs across from spawn
        'chapter': Chapters.c63_hangar,
        'arc_file': "s506.arc",
        'ap_id': 4861566},
    {'name': "6-3 Hangar RPG Shot 7", # Downstairs near spawn
        'chapter': Chapters.c63_hangar,
        'arc_file': "s506.arc",
        'ap_id': 4861567},
    {'name': "6-3 Hand Grenade at Volcano Entry",
        'chapter': Chapters.c63_volcano,
        'arc_file': "s508.arc",
        'ap_id': 4861568},
    {'name': "6-3 Red Herb at Volcano Entry",
        'chapter': Chapters.c63_volcano,
        'arc_file': "s508.arc",
        'ap_id': 4861569},
    {'name': "6-3 Rifle Ammo at Volcano Entry",
        'chapter': Chapters.c63_volcano,
        'arc_file': "s508.arc",
        'ap_id': 4861570},
    {'name': "6-3 Green Herb in Volcano Final Arena 1",
        'chapter': Chapters.c63_volcano,
        'arc_file': "s508.arc",
        'ap_id': 4861571},
    {'name': "6-3 Green Herb in Volcano Final Arena 2",
        'chapter': Chapters.c63_volcano,
        'arc_file': "s508.arc",
        'ap_id': 4861572},
    {'name': "6-3 Diamond Marquise in Volcano Final Arena",
        'chapter': Chapters.c63_volcano,
        'arc_file': "s508.arc",
        'ap_id': 4861573},
    {'name': "Satelite Laser L.T.D.",
        'chapter': Chapters.c62_aheri,
        'arc_file': "s511.arc",
        'ap_id': 4861574},
    {'name': "6-2 Flame Rounds on Upper Deck Uroboros Aheri",
        'chapter': Chapters.c62_aheri,
        'arc_file': "s511.arc",
        'ap_id': 4861575},
    {'name': "6-2 Red Herb on Upper Deck Uroboros Aheri",
        'chapter': Chapters.c62_aheri,
        'arc_file': "s511.arc",
        'ap_id': 4861576},
    {'name': "6-2 Box before Upper Deck Uroboros Aheri 1",
        'chapter': Chapters.c62_aheri,
        'arc_file': "s511.arc",
        'ap_id': 4861577},
    {'name': "6-2 Box before Upper Deck Uroboros Aheri 2",
        'chapter': Chapters.c62_aheri,
        'arc_file': "s511.arc",
        'ap_id': 4861578},
]


event_table: List[EventDict] = [
    {'name': "Chapter 1-1 Complete",
        'chapter': Chapters.c11_assembly,
        'item': "Chapter 1-1 Complete"},
    {'name': "Chapter 1-2 Complete",
        'chapter': Chapters.c12_furnace,
        'item': "Chapter 1-2 Complete"},
    {'name': "Chapter 2-1 Complete",
        'chapter': Chapters.c21_train,
        'item': "Chapter 2-1 Complete"},
    {'name': "Chapter 2-2 Complete",
        'chapter': Chapters.c22_popokarimu,
        'item': "Chapter 2-2 Complete"},
    {'name': "Chapter 3-1 Complete",
        'chapter': Chapters.c31_village,
        'item': "Chapter 3-1 Complete"},
    {'name': "Chapter 3-2 Complete",
        'chapter': Chapters.c32_docks,
        'item': "Chapter 3-2 Complete"},
    {'name': "Chapter 3-3 Complete",
        'chapter': Chapters.c33_irving,
        'item': "Chapter 3-3 Complete"},
    {'name': "Chapter 4-1 Complete",
        'chapter': Chapters.c41_labyrinth,
        'item': "Chapter 4-1 Complete"},
    {'name': "Chapter 4-2 Complete",
        'chapter': Chapters.c42_garden,
        'item': "Chapter 4-2 Complete"},
    {'name': "Chapter 5-1 Complete",
        'chapter': Chapters.c51_u8,
        'item': "Chapter 5-1 Complete"},
    {'name': "Chapter 5-2 Complete",
        'chapter': Chapters.c52_mkono,
        'item': "Chapter 5-2 Complete"},
    {'name': "Chapter 5-3 Complete",
        'chapter': Chapters.c53_jill,
        'item': "Chapter 5-3 Complete"},
    {'name': "Chapter 6-1 Complete",
        'chapter': Chapters.c61_hold,
        'item': "Chapter 6-1 Complete"},
    {'name': "Chapter 6-2 Complete",
        'chapter': Chapters.c62_aheri,
        'item': "Chapter 6-2 Complete"},       
    {'name': "6-3 Defeat Wesker",
        'chapter': Chapters.c63_volcano,
        'item': "Victory"},
]

if not ExcludeDriving == 2:
    event_table.append({
        'name': "Chapter 2-3 Complete",
           'chapter': Chapters.c23_ndesu,
           'item': "Chapter 2-3 Complete",
    })
